project: x77
queue: normal
walltime: 05:00:00
jobname: newbuild
ncpus: 454
# ncpus: 1435
# ncpus: 5634
jobfs: 10GB
shortpath: /scratch/x77

model: mom6
input:
    - /g/data/nm03/ab8992/ttide-inputs/blank-20/

exe: /g/data/v45/ab8992/mom_executables/dec-23-build
collate: false
#runlog: true
storage:
  gdata:
    - ua8
    - x77
    - ik11

mpi:
  module: openmpi/4.1.2
postscript:
  postprocessing.sh
