
#!/bin/bash
#PBS -N lftest
#PBS -P nm03
#PBS -q normalsr
#PBS -l mem=192gb
#PBS -l walltime=12:00:00
#PBS -l ncpus=96
#PBS -l jobfs=400gb
#PBS -l storage=gdata/v45+scratch/v45+scratch/x77+gdata/v45+gdata/nm03+gdata/hh5+scratch/nm03
PYTHONNOUSERSITE=1
cd /scratch/v45/ab8992/tmp
source /g/data/hh5/public/apps/miniconda3/envs/analysis3-24.04/bin/activate
python3 /home/149/ab8992/tasman-tides/lfilter.py -e full-20  -t 6480 -w 149 -o 6
