format: yamanifest
version: 1.0
---
work/INPUT/10u_ERA5.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/era5/10year/10u_ERA5.nc
  hashes:
    binhash: 0430d1cc94df568bd9990386a1d8afbb
    md5: 2b15f5f1418ccb439adf9f4aaa08e4ac
work/INPUT/10v_ERA5.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/era5/10year/10v_ERA5.nc
  hashes:
    binhash: d13959cfe9edeb3c4f7e2a0ba791cffd
    md5: 9f9c53301e782d2028bbed92e5312d25
work/INPUT/2t_ERA5.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/era5/10year/2t_ERA5.nc
  hashes:
    binhash: 61a4bb3424efb586d9305ffee400a6b8
    md5: a316e67864f070534b46d6bef398dbc2
work/INPUT/atmos_mosaic_tile1Xland_mosaic_tile1.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/atmos_mosaic_tile1Xland_mosaic_tile1.nc
  hashes:
    binhash: 5eff286462c343e92ef6d227443e41f6
    md5: ba0d1cfe6b795e04a81f46cf8dea505b
work/INPUT/atmos_mosaic_tile1Xocean_mosaic_tile1.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/atmos_mosaic_tile1Xocean_mosaic_tile1.nc
  hashes:
    binhash: 120a6c3f9563d622fd7698caf5ad2fc7
    md5: 4158dbe621b8c7de46bb97b268452fe3
work/INPUT/bathymetry_original.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/bathymetry_original.nc
  hashes:
    binhash: 8055be6653c7259890447229e7c5297b
    md5: e96f1586990957c5d01cb5dc7635f3c9
work/INPUT/bathymetry_unfinished.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/bathymetry_unfinished.nc
  hashes:
    binhash: f447deea6143097624b7cf1f8295b001
    md5: b2726f679c9f06be4387c69da3032729
work/INPUT/forcing/regrid_segment_001_tidal_elev.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/forcing/regrid_segment_001_tidal_elev.nc
  hashes:
    binhash: 04101612d73e99005e15781e914a543d
    md5: 8f112d4ccb2600bfb675182c500a8565
work/INPUT/forcing/regrid_segment_002_tidal_elev.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/forcing/regrid_segment_002_tidal_elev.nc
  hashes:
    binhash: 6f4e02c7b772dd280e40b41a282b0dc3
    md5: 0fd26562c4bede95795e8367407151ec
work/INPUT/forcing/regrid_segment_003_tidal_elev.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/forcing/regrid_segment_003_tidal_elev.nc
  hashes:
    binhash: ee0d48b1fa3edbef67834affe3d6c111
    md5: 0f0fae9b6f8e8a648ca4a96dcadf4de9
work/INPUT/forcing/regrid_segment_004_tidal_elev.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/forcing/regrid_segment_004_tidal_elev.nc
  hashes:
    binhash: fe51efce1f4a02b63a9d5864c01d1135
    md5: 55d362b6a6f75185021852bda3050281
work/INPUT/forcing_obc_segment_001.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/forcing_obc_segment_001.nc
  hashes:
    binhash: 8309fe0a5550c48b0df1d3780e975cd6
    md5: 4f62204e2aeef3b4a45bd94e40aae194
work/INPUT/forcing_obc_segment_002.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/forcing_obc_segment_002.nc
  hashes:
    binhash: 8859283f58380fea2e2977562f142baf
    md5: 5cb7015b43fdef7dcfc1375ac86ea54e
work/INPUT/forcing_obc_segment_003.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/forcing_obc_segment_003.nc
  hashes:
    binhash: 4d7f9285bae81418c9ef7e3070bf596a
    md5: 4cd689c3c757ba8420bd27fd114bd751
work/INPUT/forcing_obc_segment_004.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/forcing_obc_segment_004.nc
  hashes:
    binhash: ec671faf9d1be4e1b06612698dba5e63
    md5: 03d9569dbc49ef3c9f430767af3a544b
work/INPUT/grid_spec.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/grid_spec.nc
  hashes:
    binhash: 6a2e7c0a024fa4f2d4deec3ed2b88ec7
    md5: 12f5785978e213b8e387998cf3651662
work/INPUT/hgrid.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/hgrid.nc
  hashes:
    binhash: fd1466c43c85254b7a6fe7adcc6543db
    md5: d133a8d85a592b2c24436af3f904faca
work/INPUT/init_eta.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/init_eta.nc
  hashes:
    binhash: bf86ebcc59cb6db49bf9ac58cd8d724e
    md5: d49b1ac71f979274835bb1c2c53153f9
work/INPUT/init_tracers.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/init_tracers.nc
  hashes:
    binhash: fd1248f1e072e71549dcca0f8edc3f4c
    md5: 13996b2d4832d691ece51f5ba9b43104
work/INPUT/init_tracers_zinterp.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/init_tracers_zinterp.nc
  hashes:
    binhash: b89ed75837c23624059c0b49aeb8a109
    md5: 171109a9e1f0cc69aedf6a511a48b5ff
work/INPUT/init_vel.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/init_vel.nc
  hashes:
    binhash: 0a61d0a37e27b53e3b450c2c40b3658c
    md5: 42cdef4b141d7ffdcf6da7f90cf5a35e
work/INPUT/land_mask.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/land_mask.nc
  hashes:
    binhash: 38247f17039c5753b3318afa7b6f32a1
    md5: b8b91ed5f8554688712a2c492ce25185
work/INPUT/land_mosaic_tile1Xocean_mosaic_tile1.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/land_mosaic_tile1Xocean_mosaic_tile1.nc
  hashes:
    binhash: 2cc9f475830cef56e05529e7bf8c550e
    md5: 22d53c5c7410a8e26d34ff2033ed4b7d
work/INPUT/mask_table.104.36x30:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/mask_table.104.36x30
  hashes:
    binhash: 9819bad42c67478a4fd5bb60d47eb217
    md5: 7fa6c136326ac9ff15f1514341caf6d6
work/INPUT/mask_table.85.30x30:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/mask_table.85.30x30
  hashes:
    binhash: cb14c374e258e7a2262a9eb9095ff116
    md5: c87887dfe4999637814c1d1147b2362f
work/INPUT/msdwlwrf_ERA5.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/era5/10year/msdwlwrf_ERA5.nc
  hashes:
    binhash: b481264ef6b234b4f6d231ccc0194aa9
    md5: c53ea1e087cea76a55c6540775d5d622
work/INPUT/msdwswrf_ERA5.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/era5/10year/msdwswrf_ERA5.nc
  hashes:
    binhash: c6b587e340dd5b030976072de3915259
    md5: f6267c071cc006a14869ae788f33b985
work/INPUT/ocean_mask.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/ocean_mask.nc
  hashes:
    binhash: d85a3202dbfa89c16155df513962ec1b
    md5: 49a98763d22cee6f1e741bcf029021f3
work/INPUT/ocean_mosaic.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/ocean_mosaic.nc
  hashes:
    binhash: 0772b6c2d75e0714176c65a32b153ce5
    md5: 16f696e0babd756b0fb398099774bbf8
work/INPUT/q_ERA5.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/era5/10year/q_ERA5.nc
  hashes:
    binhash: dba222afb130cc02e88661a4e23690b2
    md5: dcbe3e00541dcee1800e3800e0be8956
work/INPUT/sp_ERA5.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/era5/10year/sp_ERA5.nc
  hashes:
    binhash: cd1b85a743220828557383a02969de5c
    md5: 2e1859f85ec81d72b26b6b1e2f397ce5
work/INPUT/topog.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/topog.nc
  hashes:
    binhash: cb475bf6b0d2886db205407ed82fbc7b
    md5: fc8230eea96ae0f2bec8dae61ad27aec
work/INPUT/topog_flattened.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/topog_flattened.nc
  hashes:
    binhash: 626ea87f304b1e77276caa2f7cc0e7ce
    md5: 4dfc14831cd1af033a3f30b9ca72cf00
work/INPUT/topog_noridge.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/topog_noridge.nc
  hashes:
    binhash: 97c077efb35b345cad0d80e87f4d7079
    md5: 3f75ba0ac3e56984bb5fe243c0dbee6b
work/INPUT/trr_ERA5.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/era5/10year/trr_ERA5.nc
  hashes:
    binhash: 7143b91ed756d71521b94de9e939ceff
    md5: ce9a1899baaaf43cb260f18ba4505b38
work/INPUT/tu_segment_001.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/tu_segment_001.nc
  hashes:
    binhash: 972da3810551cb9dc3c8ed594824de4b
    md5: 0729fef1e8b7a3cd9ec77d53d25eb4a4
work/INPUT/tu_segment_002.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/tu_segment_002.nc
  hashes:
    binhash: c2fc08109cfdba6e414ed8b99b5eba9e
    md5: 3d2556944f16ed1417ef7fa60a82919e
work/INPUT/tu_segment_003.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/tu_segment_003.nc
  hashes:
    binhash: 19d9edc54daead2b95ddd770d727759a
    md5: a8719f008b1103bfca0a5ea68298c536
work/INPUT/tu_segment_004.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/tu_segment_004.nc
  hashes:
    binhash: a85014dfdf3740906b2709233b7ac6e1
    md5: 7d79fcb13952331ae57911fde1bcdaf3
work/INPUT/tz_segment_001.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/tz_segment_001.nc
  hashes:
    binhash: 0f8297d693a9c4ac65226502b1edf745
    md5: a6186c757eafdcaf11d471acaed77e86
work/INPUT/tz_segment_002.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/tz_segment_002.nc
  hashes:
    binhash: f6870a164fff47745253fa60baf1d963
    md5: 593fb6c3c336d30836490276bc850388
work/INPUT/tz_segment_003.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/tz_segment_003.nc
  hashes:
    binhash: 2068ba8b72ec661fca652512ab54591f
    md5: 172728fc2b3c783559313363d493817d
work/INPUT/tz_segment_004.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/tz_segment_004.nc
  hashes:
    binhash: a89ea6cb0ebfaf9e7951b1d7472a2e35
    md5: 41afcdf3b7aa3bc143719a14bd7285a0
work/INPUT/vcoord.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/vcoord.nc
  hashes:
    binhash: 4cee5e636c6ae129804a6de0ce525bb1
    md5: 55ebe564c4428fa03b170c47e1ba6b51
work/INPUT/weights/bilinear_tracer_weights_east.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/weights/bilinear_tracer_weights_east.nc
  hashes:
    binhash: c6a2151f9a028e40897ca2c0daf487e6
    md5: be96ada6e9479e8d6e21a5d396d22cb1
work/INPUT/weights/bilinear_tracer_weights_north.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/weights/bilinear_tracer_weights_north.nc
  hashes:
    binhash: 3ca480eb70a32f9e4b5ca6d184f089b4
    md5: 720190e4cf02dd5f127119d486e5be74
work/INPUT/weights/bilinear_tracer_weights_south.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/weights/bilinear_tracer_weights_south.nc
  hashes:
    binhash: f030dc60773a4782537e0651abaf903a
    md5: 76c045f7dcdf8b4860a4db797d6c9111
work/INPUT/weights/bilinear_tracer_weights_west.nc:
  fullpath: /g/data/nm03/ab8992/ttide-inputs/reruns/full-20/weights/bilinear_tracer_weights_west.nc
  hashes:
    binhash: 7d15a91b6d3ee5ddc0a0c9e05515fffd
    md5: 1e851e9115e56a74b951ef40be443918
