format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart242/MOM.res.nc
  hashes:
    binhash: 551890d5b4e8f7afd0dfb362ef369080
    md5: 471ee975d40b0e801b1e528856e293d6
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart242/MOM.res_1.nc
  hashes:
    binhash: 2317dd78a915e58074e5c5face00ffac
    md5: 84b5d5a8cb6f3b64ff809c378aeecb9a
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart242/MOM.res_2.nc
  hashes:
    binhash: 2eda62d7dc8f2aa62388653697dfc0b0
    md5: 8d0ec18aefae738e36ae8d5e4863e447
work/INPUT/coupler.res:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart242/coupler.res
  hashes:
    binhash: f3f7a2b3ee66df208e4d7a9a7898cc6e
    md5: 5b24c68cb16f0e19bc9fc88b4141200e
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart242/ice_model.res.nc
  hashes:
    binhash: c8f51c6514a7eda0fce5262d92268ad1
    md5: be5f2a83b31ac26b372daddbd95557ee
