format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart130/MOM.res.nc
  hashes:
    binhash: db2797695a493aa4d955651d39405b35
    md5: 4ca523cfad28dcdb10eb1481b44332b4
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart130/MOM.res_1.nc
  hashes:
    binhash: b4f0b37851472db85288210ab0a81e1b
    md5: 94b0864b618db6f0c72d0f90513a2dbb
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart130/MOM.res_2.nc
  hashes:
    binhash: 7b3f161da8bccc755148f33eb1a4f7fb
    md5: 3a8f0287c2991e1dbdeb630be29cf7da
work/INPUT/coupler.res:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart130/coupler.res
  hashes:
    binhash: 3ed3e40eade10807e987608f5aa3fecf
    md5: e7ac761f3bd7be152ea3c98d78a5cbb3
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart130/ice_model.res.nc
  hashes:
    binhash: 49ee539bb01a42f828234d2346c0143a
    md5: b343da2cb52f534dd0d01f968d1cc23a
