format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart094/MOM.res.nc
  hashes:
    binhash: f9fd6deb78ab71829256570b7263364a
    md5: af14e3e34dcda983abbb1ff9cdfcd6b9
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart094/MOM.res_1.nc
  hashes:
    binhash: fd79588eea9cfa2eba7d7b769b85d44a
    md5: cba5d680d28b86b669808d823660c567
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart094/MOM.res_2.nc
  hashes:
    binhash: 854780bb4fc1af6470576e21bafce04b
    md5: ac67030ee4ee61fc1257c407f32e8cac
work/INPUT/coupler.res:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart094/coupler.res
  hashes:
    binhash: 49ddddfb8f5123e4bc70a6a8fc5c7296
    md5: 640bdf216bef50d9c367602209bd0ebf
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart094/ice_model.res.nc
  hashes:
    binhash: 159b17246ba394635a844e76307f3430
    md5: 036e3527a18d9bdd904dfd4c673feaba
