format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart149/MOM.res.nc
  hashes:
    binhash: fcb86fe980fed1376485ef9ac9ee9fff
    md5: b27acdb96fe1aa40ed4b8d1badfd275a
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart149/MOM.res_1.nc
  hashes:
    binhash: 0c1d87dd0d2581e8045b0e985574cbaf
    md5: 1f1bb965dec252e393a76a59395620d3
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart149/MOM.res_2.nc
  hashes:
    binhash: a36037cf4b953ae7d9b00c195f5c9a78
    md5: 5fd7f4e21cd3e7420f3eef4ff5f9b652
work/INPUT/coupler.res:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart149/coupler.res
  hashes:
    binhash: 2ea939eea08562f5827b75d061a95caf
    md5: fdd3ef0bc7e7fd563d790ba083953361
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart149/ice_model.res.nc
  hashes:
    binhash: 0ae9cf92efd69bf52f390846f2d189af
    md5: a2fae2917be8851df22ae630930bfa8f
