format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart078/MOM.res.nc
  hashes:
    binhash: c9e13404c8cb79ace1491efbf579d99c
    md5: bec6b623d48ffe5abe415607bc93d95d
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart078/MOM.res_1.nc
  hashes:
    binhash: ba0c4644b4d46887500062c9c7738b5a
    md5: a4975ec6352057f244f10871fe0b4fbe
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart078/MOM.res_2.nc
  hashes:
    binhash: 5690042d1b986ffa5e36a7c1a1432cb7
    md5: 981b9731cfc7ce72076d5d73c4bafdec
work/INPUT/coupler.res:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart078/coupler.res
  hashes:
    binhash: 0e6f043323323f2c9d93f72e226bde70
    md5: cebc5c31a10b0588156ce611bcb838d4
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart078/ice_model.res.nc
  hashes:
    binhash: 2a665b0da61add5ff7d3cf8f2d240af7
    md5: a81a7c4da5be102fbffc42cd9fdf6dff
