format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart048/MOM.res.nc
  hashes:
    binhash: ab50ae82cc52e852efe41f21fa171cd9
    md5: e51c2f49ddc527539a7798ce81003b1a
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart048/MOM.res_1.nc
  hashes:
    binhash: e79592085cafba39a9649396826035c0
    md5: d23d3f68d48920f9ce0ebfd037ce5a2e
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart048/MOM.res_2.nc
  hashes:
    binhash: b879dcdd3d7d43c5fc568e7c480c8fa1
    md5: c55cedb32eb462d80a93c87528dae198
work/INPUT/coupler.res:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart048/coupler.res
  hashes:
    binhash: 1bdc0d3079761e3a03e793683a0ced04
    md5: 166feeee40db14b45ee82917e70f4592
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart048/ice_model.res.nc
  hashes:
    binhash: 8fbeeaaf68ddb4c9dea1b930a610dc62
    md5: 142bdc39c7802c2c02304dd8058a01f4
