format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart192/MOM.res.nc
  hashes:
    binhash: 8b644a00a5984488573232542e4e9c42
    md5: 8172a6dcb4dc4d6ca7cefcb32c437547
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart192/MOM.res_1.nc
  hashes:
    binhash: b1abfeeb7e356cc8c0a3be2f9a274397
    md5: de032ed5af1037350d8a261e77ea8a47
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart192/MOM.res_2.nc
  hashes:
    binhash: 9932e53aeeec5e0cebe4024858fb2466
    md5: d29555eb5bbc97a0e9f2cc540494ddda
work/INPUT/coupler.res:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart192/coupler.res
  hashes:
    binhash: 4df36e0f84bc688597e3d613ea1bc4fc
    md5: 8a8cef90525283291cb775ca8bd83cfa
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart192/ice_model.res.nc
  hashes:
    binhash: 17d17b2a8d8189fb0b2a3212b83db4f0
    md5: efef75d6b8b29989de446a761820d4e9
