format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart058/MOM.res.nc
  hashes:
    binhash: 829ec7c4d2749f182e59b0fb97908072
    md5: 9aaba51fb83268a9878364ede500c9c0
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart058/MOM.res_1.nc
  hashes:
    binhash: ca7dd9448653ca2cb0763040d683abfa
    md5: 264dcd78ba2c83b204d3cd3dd9a99c26
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart058/MOM.res_2.nc
  hashes:
    binhash: 4da2d6b54d2580af9a2b06eabd6f212a
    md5: ebd48beedd0c91494668088c41fde8e5
work/INPUT/coupler.res:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart058/coupler.res
  hashes:
    binhash: e7042bda22bc7b7cfa72c7aecbcffe30
    md5: 724de1fd134db8fb531a356cb51bd059
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart058/ice_model.res.nc
  hashes:
    binhash: b3ece93ff174495ce38db9ed9ae994de
    md5: 783138f9b067c6ba8fa1cac60ad7c6fc
