format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart017/MOM.res.nc
  hashes:
    binhash: eb4431cecb9c6d625a4979471a8be9ca
    md5: 9ce3f86be17bd9a71ae19067a5eb06f9
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart017/MOM.res_1.nc
  hashes:
    binhash: 97a063fdd4b63815c5dc04542b5a7ce5
    md5: ecf76e55f633aedac03593dca678821a
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart017/MOM.res_2.nc
  hashes:
    binhash: f121842dfbb44e5b0ced1748fdae1172
    md5: 411c86380abdb84e58bf81ee859d575c
work/INPUT/coupler.res:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart017/coupler.res
  hashes:
    binhash: c87cd64e60c40e1c869b4df33e729cf8
    md5: 15caa3bdf816f49cf7c36a27a6c55c00
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/notide-20/restart017/ice_model.res.nc
  hashes:
    binhash: 840e1cdb585bee1806425ceee54cd0ff
    md5: 4955f663b899407bde0c2c85d77bbdea
