format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/blank-20/restart001/MOM.res.nc
  hashes:
    binhash: ca7c1d534bf532d8361b4c662ab2ca5c
    md5: 5cf16c27daa3d668cae8158db2282aca
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/blank-20/restart001/MOM.res_1.nc
  hashes:
    binhash: 209b0e3cef64625614bcd9abad70cc4d
    md5: 65ea990e24f3b23f91f05dfcbb1d5f4e
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/blank-20/restart001/MOM.res_2.nc
  hashes:
    binhash: 148eb39c4c218db64c87384bb315074c
    md5: bc3e2b4346dfbdd09b4c3efe95954149
work/INPUT/ocean_solo.res:
  fullpath: /scratch/nm03/ab8992/mom6/archive/blank-20/restart001/ocean_solo.res
  hashes:
    binhash: 8fa656e3a9855854126b5c854a181747
    md5: 3fe649aa4b402e4d7a05b64f7edc444f
