format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/x77/ab8992/mom6/archive/excavated-alltides-blank-20/restart007/MOM.res.nc
  hashes:
    binhash: e51d14624691e1e4c5a66cf810cb2e8d
    md5: e88e31084e963caba53f8d986bf588c1
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/x77/ab8992/mom6/archive/excavated-alltides-blank-20/restart007/MOM.res_1.nc
  hashes:
    binhash: b7aef193c9201bb883fb662d21ba8397
    md5: 9b111fc8676d5fe042a2001dcf9f751d
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/x77/ab8992/mom6/archive/excavated-alltides-blank-20/restart007/MOM.res_2.nc
  hashes:
    binhash: d457c672dc121d669c2a1c1b60133ae4
    md5: 696a2d77ec82cb94e5f55a4ed824babe
work/INPUT/coupler.res:
  fullpath: /scratch/x77/ab8992/mom6/archive/excavated-alltides-blank-20/restart007/coupler.res
  hashes:
    binhash: 722c85ba28b1090fe13c36a8744075da
    md5: 5978d9718c6367f0a64955718677b9ee
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/x77/ab8992/mom6/archive/excavated-alltides-blank-20/restart007/ice_model.res.nc
  hashes:
    binhash: 4de6ca91177ea00afdd0ffe6502dc2d0
    md5: 89ac6688d6ce4ff90d620126741e2788
