format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/nonudging-blank-20/restart016/MOM.res.nc
  hashes:
    binhash: 35d47afb09a75609e973db2b242f8467
    md5: 31eb929d967cac26be10f2987cc64c3e
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/nonudging-blank-20/restart016/MOM.res_1.nc
  hashes:
    binhash: 4fc7ab4e7f9694253e6715078c83ff08
    md5: 7c70f953b0df327f45fecb6651e570fd
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/nonudging-blank-20/restart016/MOM.res_2.nc
  hashes:
    binhash: f12e396855a15fa5a874365b219abca8
    md5: e59e6d13bfe149e5b541f2130e89c81e
work/INPUT/ocean_solo.res:
  fullpath: /scratch/nm03/ab8992/mom6/archive/nonudging-blank-20/restart016/ocean_solo.res
  hashes:
    binhash: cfa45b5b49d98fb0623b905939cfc30e
    md5: f66dfc23e8a32846d74f26b458baf560
