format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/x77/ab8992/mom6/archive/excavated-blank-20/restart009/MOM.res.nc
  hashes:
    binhash: e929715c45c97d6a0554fd7270f4bc88
    md5: 16109e40e62f4efb8ea74982c7ef75c3
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/x77/ab8992/mom6/archive/excavated-blank-20/restart009/MOM.res_1.nc
  hashes:
    binhash: 50de22f9ed091e98e23ab6c7a6a5dfac
    md5: b50557d809098ffd8d99c38c48111f3f
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/x77/ab8992/mom6/archive/excavated-blank-20/restart009/MOM.res_2.nc
  hashes:
    binhash: 18cb132ffc9ffc671b27cea8d0598956
    md5: e23745d75512cca3f88d34f441bbc452
work/INPUT/coupler.res:
  fullpath: /scratch/x77/ab8992/mom6/archive/excavated-blank-20/restart009/coupler.res
  hashes:
    binhash: 862bdf94084d8d74e72fa2aa97ec78fa
    md5: b183d38f30bd40994e323822544705fa
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/x77/ab8992/mom6/archive/excavated-blank-20/restart009/ice_model.res.nc
  hashes:
    binhash: ceeac2e2a2529b488e80e9491098d1bb
    md5: 4df7dbfc2e5b15c911beb796dbadc04f
