project: x77
queue: normal
walltime: 06:00:00
jobname: mom6_testtides-20
ncpus: 454
jobfs: 10GB
shortpath: /scratch/x77

model: mom6
input:
#    - /g/data/nm03/ab8992/ttide-inputs/default/
    - /g/data/nm03/ab8992/ttide-inputs/blank-ttide-20-synbath/
# release exe
# exe: /g/data/x77/ahg157/exes/MOM6_SIS2/symmetric_FMS2-e7d09b7
# debug exe
#exe: /g/data/x77/ahg157/exes/MOM6_SIS2/symmetric_FMS2-9bc3419a
exe: /g/data/v45/ab8992/mom_executables/angus_fms
collate: false
#runlog: true
storage:
  gdata:
    - ua8
    - x77
    - ik11

mpi:
  module: openmpi/4.1.2
postscript:
  postprocessing.sh
