project: x77
queue: normal
walltime: 05:00:00
jobname: smooth-40
ncpus: 1435
#ncpus: 3639
jobfs: 10GB
shortpath: /scratch/nm03

model: mom6
input:
    - /g/data/nm03/ab8992/ttide-inputs/era5/10year
    - /g/data/nm03/ab8992/ttide-inputs/full-40/
    - /g/data/nm03/ab8992/ttide-inputs/smooth-40
exe: /g/data/v45/ab8992/mom_executables/jan2024-latest-everything-mod
collate: false
runlog: false
storage:
  gdata:
    - ua8
    - x77
    - ik11

mpi:
  module: openmpi/4.1.2
postscript:
  postprocessing.sh
userscripts:
  error: resub.sh
  run: rm -f resubmit.count
