format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/full-20/restart113/MOM.res.nc
  hashes:
    binhash: 2a8d9db2af749eb74fed84dc02cbf5d8
    md5: f144980cb2fd954fca30cd61b4671ebb
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/full-20/restart113/MOM.res_1.nc
  hashes:
    binhash: fdedd75c80441bd1cd1dc733a4a89f2d
    md5: 3dfe077b3ab33c711fc5f975a020727d
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/full-20/restart113/MOM.res_2.nc
  hashes:
    binhash: 2753dc2c5da43fd0b7aabe18d6aa3c00
    md5: e9de830f0cf77c4d0cd7b1c0d1841944
work/INPUT/coupler.res:
  fullpath: /scratch/nm03/ab8992/mom6/archive/full-20/restart113/coupler.res
  hashes:
    binhash: 9c928b0db6aa767bf20e845d6b0eb2c6
    md5: b4829c95dddab028a2a875cf587299b3
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/full-20/restart113/ice_model.res.nc
  hashes:
    binhash: b7553c1903cdd72742392a2a2d6825be
    md5: 52a062ed8cd160343609001060eb788e
