format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/full-20/restart163/MOM.res.nc
  hashes:
    binhash: c554b16437cd2e5613313cde052f97f6
    md5: c92b765810aa9d72cb431adcbe5580cc
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/full-20/restart163/MOM.res_1.nc
  hashes:
    binhash: a9d384f8cf4dbc6468a52a1551b3aaa6
    md5: 07c6825f83e33cc764863fe97175cb32
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/full-20/restart163/MOM.res_2.nc
  hashes:
    binhash: 1d1db8436d86f790cc77ec463ae297c7
    md5: 44b5002badce0b1ffe8ee9e5effabf8c
work/INPUT/coupler.res:
  fullpath: /scratch/nm03/ab8992/mom6/archive/full-20/restart163/coupler.res
  hashes:
    binhash: b87c6bbadd88ed4c0e9cb8dbe2ed3ca7
    md5: 515ea868628f98fff0ee3751963e3502
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/nm03/ab8992/mom6/archive/full-20/restart163/ice_model.res.nc
  hashes:
    binhash: 34c92e8e26c96e688725ea803936bae5
    md5: 4c4ec5ae121a89dff5887beebf3772f9
