project: nm03
queue: normal
walltime: 05:00:00
jobname: smooth-10
ncpus: 822
jobfs: 10GB
shortpath: /scratch/nm03

model: mom6
input:
    - /g/data/nm03/ab8992/ttide-inputs/era5/10year
    - /g/data/nm03/ab8992/ttide-inputs/full-10/

exe: /g/data/v45/ab8992/mom_executables/jan2024-latest-everything-mod
#exe: /g/data/v45/ab8992/mom_executables/angus_fms
collate: false
runlog: false
storage:
  gdata:
    - ua8
    - x77
    - ik11

mpi:
  module: openmpi/4.1.2
postscript:
  postprocessing.sh
userscripts:
  error: resub.sh
  run: rm -f resubmit.count

