format: yamanifest
version: 1.0
---
work/jan2024-latest-everything:
  fullpath: /g/data/v45/ab8992/mom_executables/jan2024-latest-everything
  hashes:
    binhash: 6ac5dd48bc6893e881f7b91494e2235f
    md5: 95d722182e0af82dcd54ad3ad3587dad
