format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/x77/ab8992/mom6/archive/fullexpt-test/restart006/MOM.res.nc
  hashes:
    binhash: 1a6ed462b9238f5103aa737626215a7f
    md5: 576af66c611786c1c716ed00a3f1fd62
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/x77/ab8992/mom6/archive/fullexpt-test/restart006/MOM.res_1.nc
  hashes:
    binhash: f8622a6b7c1c8094f8aad0393f12f281
    md5: c964e31eacd78592bc0864e25ea0c942
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/x77/ab8992/mom6/archive/fullexpt-test/restart006/MOM.res_2.nc
  hashes:
    binhash: 302fbada44c57d34caab0e389986531f
    md5: 37c9a0c87f58b71968a3cbc3f4cff99c
work/INPUT/coupler.res:
  fullpath: /scratch/x77/ab8992/mom6/archive/fullexpt-test/restart006/coupler.res
  hashes:
    binhash: de217ec2ebdf2faec335930779b9d349
    md5: 653b2c0fa95d534d67bfa36488718fa8
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/x77/ab8992/mom6/archive/fullexpt-test/restart006/ice_model.res.nc
  hashes:
    binhash: 4087d1d65c4c9fdfb3786221e4d0e2bf
    md5: 6d2d33c67999ef4ecd55e5e329ec1053
